{"name": "Unsuccessful login", "status": "passed", "description": "Checking successful login with incorrect credentials", "steps": [{"name": "validate error name", "status": "passed", "parameters": [{"name": "error_name", "value": "'incorrect'"}], "start": 1679649044668, "stop": 1679649044770}, {"name": "validate error password", "status": "passed", "parameters": [{"name": "error_password", "value": "'incorrect'"}], "start": 1679649044770, "stop": 1679649044848}, {"name": "clicking to login button", "status": "passed", "start": 1679649044848, "stop": 1679649044908}, {"name": "validate error message", "status": "passed", "parameters": [{"name": "error_message", "value": "'Epic sadface: Username and password do not match any user in this service'"}], "start": 1679649044908, "stop": 1679649044943}], "parameters": [{"name": "error_name", "value": "'incorrect'"}, {"name": "error_password", "value": "'incorrect'"}, {"name": "error_message", "value": "'Epic sadface: Username and password do not match any user in this service'"}], "start": 1679649044668, "stop": 1679649044943, "uuid": "0c60dcac-27dc-461b-a82d-c47aaef51b26", "historyId": "9a7837802be43f64432b598f9ed30ef8", "testCaseId": "a7c18bc2d0a4e903f0cff3007abfbc12", "fullName": "tests.test_index_page#test_unsuccessful_login", "labels": [{"name": "severity", "value": "blocker"}, {"name": "owner", "value": "Vlad"}, {"name": "suite", "value": "Authorization suite"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "DESKTOP-SO90PSP"}, {"name": "thread", "value": "27152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_index_page"}]}